/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coordinatorlayout;

public final class Recipe_Ingredient {
    internal lateinit var quty: String
    internal lateinit var measuretype: String
    internal lateinit var ingr_name: String

    constructor(quty: String, measuretype: String, ingr_name: String) {
        this.quty = quty
        this.measuretype = measuretype
        this.ingr_name = ingr_name
    }
}